version: '3'
services:
  hub:
    image: selenium/hub:4.23.0
    shm_size: '2g'
    ports:
    - 4444:4444
#  jenkins:
#    image: jenkins/jenkins:lts
#    user: root
#    ports:
#    - 8080:8080
#    - 50000:50000
#    volumes:
#    - ./volumes/master:/var/jenkins_home

  chrome:
    image: selenium/node-chrome:127.0
    depends_on:
      - hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
  firefox:
    image: selenium/node-firefox:128.0
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
  edge:
    image: selenium/node-edge:127.0
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 0
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2

  flight-reservation:
    image: sgnsabir/selenium
    depends_on:
      - chrome
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=2
    - TEST_SUITE=flight-reservation.xml
    volumes:
    - ./output/flight-reservation:/home/selenium-docker/test-output 

  vendor-portal:
    image: sgnsabir/selenium
    depends_on:
      - firefox
    environment:
    - BROWSER=firefox
    - HUB_HOST=hub
    - THREAD_COUNT=2
    - TEST_SUITE=vendor-portal.xml
    volumes:
    - ./output/vendor-portal:/home/selenium-docker/test-output

#command
# To run Jenkins: uncomment jenkins  and then docker-compose up, go to volumes/node then execute following commands 
# curl -s0 http://localhost:jnlpJars/agent.jar
# java -jar agent.jar -url http://localhost:8080/ -secret 571e338139a31ec37e2f8cd3d72e1841cdc4d2ab2a520cea72fac8b18e579c40 -name NODE1 -workDir "/home/sabir/workspace/06-jenkins-ci-cd/01-jenkins/volumes/node"
# go to localhost:8080 for jenkins